# Generated by Django 5.0.7 on 2024-07-17 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4c2f83f0-0ec3-47bb-a0cf-8e0ce0c901a2'), primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('profile_img', models.ImageField(upload_to='user/profile_imgs')),
            ],
        ),
    ]
