# Generated by Django 5.0.7 on 2024-07-19 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ad5dbd4-1282-44ca-8f2d-366249a9be65'), primary_key=True, serialize=False),
        ),
    ]
